#!/usr/bin/env node
// Build a static distribution of the formalization viewer under <root>/dist.
//
// The dist directory mirrors the URL space of serve.ts, so serving it with any
// static file server reproduces the live viewer, minus the Lean LSP bridge and
// the file watcher:
//
//   <dist>/<mount>/...   one URL tree holding the viewer assets, manifest.json
//                        (with "static": true so the browser uses the LSP cache
//                        instead of the /lsp bridge), the project files the live
//                        server allowlists, and the pregenerated lsp-cache/
//   <dist>/index.html    redirect to the mount
//
// --base-path <seg> nests that whole tree one directory deeper, so the dist is
// served from a subdirectory of the host root: <dist>/<base>/<mount>/...,
// <dist>/<base>/index.html redirects to the mount, and the top-level
// <dist>/index.html redirects on into <base>/<mount>/. This is for a custom
// apex domain that should expose the viewer under a path prefix (e.g.
// sunaemon.dev/math/<mount>/ rather than sunaemon.dev/<mount>/); the browser
// derives the prefix from the URL at runtime (util.ts mountPrefix), so no asset
// path changes are needed. Empty (the default) keeps the mount at the host root.
//
// --legacy-redirect <path> (repeatable) leaves a stub at <dist>/<path>/index.html
// forwarding an old host-root URL that used to serve this book on to its current
// location. It is an explicit per-URL migration aid for a book that was already
// published before a move, not an automatic effect of --base-path: a book that
// never had the old URL (a newly published one) passes no --legacy-redirect and
// so gets no host-root stub.
//
// The LSP cache is generated by lsp-cache.ts into the project build directory
// (so it survives dist rebuilds and is reused incrementally) and copied in.
// `lake build` runs first so every Lean file elaborates from cached oleans.

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import { generate } from "./lsp-cache.ts";
import { repoVersion, attachLicenseText, appendVendorComponents, katexMacros, macrosTexPath } from "./repo-version.ts";

const VIEWER_DIR = "tools/formalization-viewer";
// Build-time-only subtrees of the viewer dir that must not ship in the dist:
// the TypeScript browser sources (only the transpiled build/ .js is shipped) and
// the Node server (the dist is served statically).
const VIEWER_EXCLUDE = new Set(["src", "server"]);

const REDIRECT_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url={target}">
  <title>formalization viewer</title>
</head>
<body><a href="{target}">formalization viewer</a></body>
</html>
`;

interface Manifest {
  mount: string;
  dir: string;
  served?: Record<string, string[]>;
  flat?: string[];
  license?: unknown;
  [key: string]: unknown;
}

function assetHash(p: string): string {
  return createHash("sha256").update(fs.readFileSync(p)).digest("hex").slice(0, 10);
}

// Append a content-hash `?v=` query to the viewer's own CSS/JS in index.html, so
// a rebuilt dist automatically busts any cached copy. Idempotent.
function stampAssetVersions(mountDir: string): void {
  const indexPath = path.join(mountDir, "index.html");
  if (!fs.existsSync(indexPath)) return;
  let html = fs.readFileSync(indexPath, "utf-8");
  const assets: Record<string, string> = {
    "./styles.css": path.join(mountDir, "styles.css"),
    "./build/app.js": path.join(mountDir, "build", "app.js"),
  };
  for (const [ref, p] of Object.entries(assets)) {
    if (!fs.existsSync(p)) continue;
    const version = assetHash(p);
    const escaped = ref.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    html = html.replace(new RegExp(`${escaped}(\\?v=[^"']*)?`, "g"), `${ref}?v=${version}`);
  }
  fs.writeFileSync(indexPath, html);
}

function validateManifest(p: string, meta: unknown): asserts meta is Manifest {
  if (meta === null || typeof meta !== "object" || Array.isArray(meta)) {
    throw new Error(`${p}: expected a JSON object at the top level.`);
  }
  const mount = (meta as Manifest).mount;
  if (typeof mount !== "string" || !mount.startsWith("/") || mount.replace(/\/+$/, "") === "") {
    throw new Error(`${p}: missing or invalid string field "mount".`);
  }
  const served = (meta as Manifest).served;
  if (served !== undefined && (served === null || typeof served !== "object" || Array.isArray(served))) {
    throw new Error(`${p}: "served" must be an object of subdir -> extensions.`);
  }
}

function loadProject(root: string): Manifest {
  const named = (process.env.BOOKLINK_PROJECT ?? "").trim();
  const candidates = named
    ? [named]
    : fs
        .readdirSync(root)
        .filter((entry) => {
          try {
            return fs.statSync(path.join(root, entry, "manifest.json")).isFile();
          } catch {
            return false;
          }
        })
        .sort();
  for (const dirname of candidates) {
    const p = path.join(root, dirname, "manifest.json");
    if (fs.existsSync(p) && fs.statSync(p).isFile()) {
      const meta = JSON.parse(fs.readFileSync(p, "utf-8"));
      validateManifest(p, meta);
      if (meta.dir === undefined) meta.dir = dirname;
      return meta;
    }
  }
  throw new Error("No project manifest found (expected <dir>/manifest.json under the repo root).");
}

function* walkFiles(top: string): Generator<string> {
  const seen = new Set<string>();
  const stack = [top];
  while (stack.length) {
    const dir = stack.pop()!;
    let real: string;
    try {
      real = fs.realpathSync(dir);
    } catch {
      continue;
    }
    if (seen.has(real)) continue;
    seen.add(real);
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      let isDir = entry.isDirectory();
      let isFile = entry.isFile();
      if (entry.isSymbolicLink()) {
        try {
          const st = fs.statSync(full);
          isDir = st.isDirectory();
          isFile = st.isFile();
        } catch {
          continue; // broken symlink
        }
      }
      if (isDir) stack.push(full);
      else if (isFile) yield full;
    }
  }
}

// Copy the files the live server allowlists into the mount tree: each served
// subdirectory restricted to its extensions, with `flat` directories kept
// top-level only.
function copyServedFiles(root: string, project: Manifest, mountDir: string): number {
  const projectRoot = path.join(root, project.dir);
  const flat = new Set(project.flat ?? []);
  let copied = 0;
  for (const [sub, exts] of Object.entries(project.served ?? {})) {
    const allowed = new Set(exts.map((ext) => `.${ext}`));
    const srcDir = path.join(projectRoot, sub);
    try {
      if (!fs.statSync(srcDir).isDirectory()) continue;
    } catch {
      continue;
    }
    for (const src of walkFiles(srcDir)) {
      if (!allowed.has(path.extname(src))) continue;
      if (flat.has(sub) && path.dirname(src) !== srcDir) continue;
      const rel = path.relative(projectRoot, src);
      const dest = path.join(mountDir, rel);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.copyFileSync(src, dest);
      copied += 1;
    }
  }
  return copied;
}

function mountPdfList(mountDir: string): string[] {
  const found = new Set<string>();
  for (const full of walkFiles(mountDir)) {
    if (full.toLowerCase().endsWith(".pdf")) {
      found.add(path.relative(mountDir, full).split(path.sep).join("/"));
    }
  }
  return [...found].sort();
}

interface DistArgs {
  root: string;
  dist: string | null;
  basePath: string;
  legacyRedirects: string[];
  noLakeBuild: boolean;
  skipLspCache: boolean;
}

// Treat a CLI path option strictly as a hosted-URL prefix: a run of plain "/"-
// separated segments that will be path.join'd into the dist tree and emitted into
// relative redirect targets. Trim surrounding slashes, then reject anything that
// could escape the tree or split a redirect — absolute paths, "." / ".." segments,
// empty segments from doubled slashes, and backslashes (never valid in a URL path,
// and a separator path.join would honor on Windows, reopening the "..\\" escape).
// Returns the normalized slash-free prefix, or "" for empty input (the default).
function normalizePrefix(raw: string, flag: string): string {
  const trimmed = raw.replace(/^\/+|\/+$/g, "");
  if (trimmed === "") return "";
  for (const seg of trimmed.split("/")) {
    if (seg === "" || seg === "." || seg === ".." || seg.includes("\\")) {
      throw new Error(
        `${flag}: invalid path "${raw}"; expected a plain URL prefix of "/"-separated segments with no "." / ".." parts or backslashes.`,
      );
    }
  }
  return trimmed;
}

function parseArgs(argv: string[]): DistArgs {
  const args: DistArgs = {
    root: ".",
    dist: null,
    basePath: "",
    legacyRedirects: [],
    noLakeBuild: false,
    skipLspCache: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--root") args.root = argv[++i];
    else if (arg === "--dist") args.dist = argv[++i];
    else if (arg === "--base-path") args.basePath = argv[++i];
    else if (arg === "--legacy-redirect") args.legacyRedirects.push(argv[++i]);
    else if (arg === "--no-lake-build") args.noLakeBuild = true;
    else if (arg === "--skip-lsp-cache") args.skipLspCache = true;
  }
  // Validate and normalize to bare slash-free segment paths so they compose
  // cleanly into both the on-disk layout and the relative redirect targets below,
  // and cannot escape the dist tree.
  args.basePath = normalizePrefix(args.basePath, "--base-path");
  args.legacyRedirects = args.legacyRedirects.map((p) => normalizePrefix(p, "--legacy-redirect")).filter(Boolean);
  return args;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const root = path.resolve(args.root);
  const project = loadProject(root);
  const projectDir = project.dir;
  const mount = project.mount.replace(/^\/+|\/+$/g, "");
  const basePath = args.basePath;
  const dist = path.resolve(args.dist ?? path.join(root, "dist"));
  const cacheDir = path.join(root, projectDir, "build", "lsp-cache");

  if (!args.skipLspCache) {
    if (!args.noLakeBuild) {
      process.stdout.write("lsp-cache: running lake build...\n");
      execFileSync("lake", ["build"], { cwd: path.join(root, projectDir), stdio: "inherit" });
    }
    await generate(root, projectDir, cacheDir);
  }

  if (fs.existsSync(dist)) fs.rmSync(dist, { recursive: true, force: true });

  // Viewer assets live at the mount, exactly where applyMount routes them, under
  // any --base-path prefix. The TypeScript sources (src/) and the Node server
  // (server/) are build-only.
  const mountDir = path.join(dist, basePath, mount);
  fs.cpSync(path.join(root, VIEWER_DIR), mountDir, {
    recursive: true,
    filter: (src) => {
      const rel = path.relative(path.join(root, VIEWER_DIR), src);
      const top = rel.split(path.sep)[0];
      return !VIEWER_EXCLUDE.has(top);
    },
  });
  const copied = copyServedFiles(root, project, mountDir);
  stampAssetVersions(mountDir);

  const staticManifest: Manifest = structuredClone(project);
  staticManifest.static = true;
  staticManifest.version = repoVersion(root);
  if (staticManifest.license) {
    appendVendorComponents(root, staticManifest.license);
    staticManifest.license = attachLicenseText(root, staticManifest.license);
  }
  staticManifest.katexMacros = katexMacros(macrosTexPath(root, projectDir));
  staticManifest.pdfs = mountPdfList(mountDir);
  fs.writeFileSync(path.join(mountDir, "manifest.json"), JSON.stringify(staticManifest, null, 2));

  if (fs.existsSync(cacheDir)) {
    fs.cpSync(cacheDir, path.join(mountDir, "lsp-cache"), { recursive: true });
  }

  // Redirect the host root on into the mount. With a --base-path the top-level
  // redirect hops through the prefix, and a second redirect at the prefix root
  // lands a bare <base>/ visit on the book too. Redirect targets are relative to
  // the file's own directory, so each is just the path from there to the mount.
  const newHome = basePath ? `${basePath}/${mount}` : mount;
  fs.writeFileSync(path.join(dist, "index.html"), REDIRECT_HTML.replace(/\{target\}/g, `${newHome}/`));
  if (basePath) {
    fs.mkdirSync(path.join(dist, basePath), { recursive: true });
    fs.writeFileSync(path.join(dist, basePath, "index.html"), REDIRECT_HTML.replace(/\{target\}/g, `${mount}/`));
  }

  // Each --legacy-redirect names an old host-root URL that used to serve this
  // book before it moved to newHome; leave a stub there forwarding bookmarked or
  // indexed pre-move links on. Explicit and per-URL, so a book that never had the
  // old URL gets no stub. One "../" per old segment climbs back to the host root
  // before re-descending into newHome. Skip a path that would land on (and clobber)
  // a real redirect or the mount tree itself.
  for (const old of args.legacyRedirects) {
    if (old === newHome || (basePath && old === basePath)) {
      process.stdout.write(`Skipping --legacy-redirect ${old}: it collides with the live layout.\n`);
      continue;
    }
    fs.mkdirSync(path.join(dist, old), { recursive: true });
    const up = "../".repeat(old.split("/").length);
    fs.writeFileSync(path.join(dist, old, "index.html"), REDIRECT_HTML.replace(/\{target\}/g, `${up}${newHome}/`));
  }
  // GitHub Pages serves the tree through Jekyll unless told not to.
  fs.writeFileSync(path.join(dist, ".nojekyll"), "");

  const relDist = path.relative(root, dist);
  const port = (process.env.BOOKLINK_VIEWER_PORT ?? "8000").trim() || "8000";
  const urlPath = basePath ? `${basePath}/${mount}/` : `${mount}/`;
  process.stdout.write(`Static viewer: ${copied} project files + viewer assets in ${relDist}/\n`);
  process.stdout.write(`Standalone serve with: python3 -m http.server ${port} --bind 127.0.0.1 -d ${relDist}\n`);
  process.stdout.write(`Then open: http://127.0.0.1:${port}/${urlPath}\n`);
}

void main();
